"""Add scrape metrics, baselines, and alerts tables plus two dashboard views.

Priority 5 — Per-field fill-rate tracking + alerting.

Tables:
  scrape_run_metrics         — per-run, per-field, per-method fill-rate counts
  university_field_baselines — expected fill rates per university per field
  scrape_run_alerts          — alert rows generated by the evaluator

Views:
  v_university_run_health    — latest run health per university
  v_field_health_trend       — top deteriorating fields across all universities

Revision ID: 009_add_metrics_alerts
Revises: 008_add_test_accepted_flags
Create Date: 2026-04-29
"""
from __future__ import annotations

from alembic import op

revision = "009_add_metrics_alerts"
down_revision = "008_add_test_accepted_flags"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS scrape_run_metrics (
            id          BIGSERIAL PRIMARY KEY,
            scrape_run_id TEXT NOT NULL
                REFERENCES scrape_runtime_jobs(runtime_job_id) ON DELETE CASCADE,
            university_id INT NOT NULL,
            field_key   VARCHAR(64) NOT NULL,
            method      VARCHAR(64) NOT NULL,
            count       INT NOT NULL,
            courses_total INT NOT NULL,
            fill_rate   NUMERIC(5,4) NOT NULL,
            computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_run_metrics_run ON scrape_run_metrics(scrape_run_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_run_metrics_uni_field ON scrape_run_metrics(university_id, field_key)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_run_metrics_method ON scrape_run_metrics(method)")

    op.execute("""
        CREATE TABLE IF NOT EXISTS university_field_baselines (
            id                          BIGSERIAL PRIMARY KEY,
            university_id               INT NOT NULL,
            field_key                   VARCHAR(64) NOT NULL,
            expected_fill_rate          NUMERIC(5,4) NOT NULL,
            expected_method_distribution JSONB NOT NULL DEFAULT '{}'::jsonb,
            floor_threshold             NUMERIC(5,4) NOT NULL,
            sample_size                 INT NOT NULL,
            last_updated                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            UNIQUE(university_id, field_key)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_baselines_uni ON university_field_baselines(university_id)")

    op.execute("""
        CREATE TABLE IF NOT EXISTS scrape_run_alerts (
            id              BIGSERIAL PRIMARY KEY,
            scrape_run_id   TEXT NOT NULL
                REFERENCES scrape_runtime_jobs(runtime_job_id) ON DELETE CASCADE,
            rule_id         VARCHAR(128) NOT NULL,
            severity        VARCHAR(16) NOT NULL,
            message         TEXT NOT NULL,
            expected        NUMERIC,
            actual          NUMERIC,
            acknowledged    BOOLEAN NOT NULL DEFAULT false,
            acknowledged_by VARCHAR(128),
            acknowledged_at TIMESTAMPTZ,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_run_alerts_run ON scrape_run_alerts(scrape_run_id)")
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_run_alerts_unack_critical
        ON scrape_run_alerts(severity, acknowledged)
        WHERE severity = 'critical' AND acknowledged = false
    """)

    op.execute("""
        CREATE OR REPLACE VIEW v_university_run_health AS
        SELECT
            u.id AS university_id,
            u.name,
            j.runtime_job_id AS scrape_run_id,
            j.completed_at,
            COUNT(a.id) FILTER (WHERE a.severity = 'critical') AS critical_alerts,
            COUNT(a.id) FILTER (WHERE a.severity = 'warning')  AS warning_alerts,
            array_agg(DISTINCT a.rule_id) FILTER (WHERE a.severity = 'critical') AS critical_rule_ids
        FROM universities u
        JOIN scrape_runtime_jobs j ON j.university_id = u.id
        LEFT JOIN scrape_run_alerts a ON a.scrape_run_id = j.runtime_job_id
        WHERE j.completed_at = (
            SELECT MAX(j2.completed_at)
            FROM scrape_runtime_jobs j2
            WHERE j2.university_id = u.id AND j2.status = 'completed'
        )
        GROUP BY u.id, u.name, j.runtime_job_id, j.completed_at
        ORDER BY critical_alerts DESC, warning_alerts DESC
    """)

    op.execute("""
        CREATE OR REPLACE VIEW v_field_health_trend AS
        SELECT
            field_key,
            AVG(fill_rate) FILTER (WHERE rn <= 5)             AS recent_avg,
            AVG(fill_rate) FILTER (WHERE rn BETWEEN 6 AND 10) AS previous_avg,
            AVG(fill_rate) FILTER (WHERE rn <= 5) -
                AVG(fill_rate) FILTER (WHERE rn BETWEEN 6 AND 10) AS delta
        FROM (
            SELECT
                m.*,
                ROW_NUMBER() OVER (
                    PARTITION BY m.university_id, m.field_key
                    ORDER BY m.computed_at DESC
                ) AS rn
            FROM scrape_run_metrics m
        ) ranked
        WHERE rn <= 10
        GROUP BY field_key
        HAVING AVG(fill_rate) FILTER (WHERE rn BETWEEN 6 AND 10) IS NOT NULL
        ORDER BY delta ASC
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_field_health_trend")
    op.execute("DROP VIEW IF EXISTS v_university_run_health")
    op.execute("DROP TABLE IF EXISTS scrape_run_alerts CASCADE")
    op.execute("DROP TABLE IF EXISTS university_field_baselines CASCADE")
    op.execute("DROP TABLE IF EXISTS scrape_run_metrics CASCADE")
