"""initial_migration

Revision ID: a505b2e5b1f1
Revises: 
Create Date: 2026-05-28 16:45:15.359168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a505b2e5b1f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_level_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bulk_sessions',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('fast_mode', sa.Boolean(), nullable=False),
    sa.Column('unis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('central_page_cache',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('university_id', 'page_type')
    )
    op.create_table('course_acronym_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acronym', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scraper_config_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('saved_by', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('scrape_url', sa.Text(), nullable=True),
    sa.Column('fee_page_url', sa.Text(), nullable=True),
    sa.Column('requirements_page_url', sa.Text(), nullable=True),
    sa.Column('scholarship_page_url', sa.Text(), nullable=True),
    sa.Column('academic_requirements_page_url', sa.Text(), nullable=True),
    sa.Column('scrape_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('featured_priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university_field_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('expected_fill_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('expected_method_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('floor_threshold', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id', 'field_key', name='uq_baseline_uni_field')
    )
    op.create_table('assessment_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('sub_category', sa.Text(), nullable=True),
    sa.Column('course_website', sa.Text(), nullable=True),
    sa.Column('duration', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_term', sa.Text(), nullable=True),
    sa.Column('study_mode', sa.Text(), nullable=True),
    sa.Column('degree_level', sa.Text(), nullable=True),
    sa.Column('study_load', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_structure', sa.Text(), nullable=True),
    sa.Column('career_outcomes', sa.Text(), nullable=True),
    sa.Column('other_test', sa.Text(), nullable=True),
    sa.Column('other_test_score', sa.Text(), nullable=True),
    sa.Column('other_requirement', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('course_location', sa.Text(), nullable=True),
    sa.Column('student_market', sa.Text(), nullable=True),
    sa.Column('delivery_mode', sa.Text(), nullable=True),
    sa.Column('international_eligible', sa.Boolean(), nullable=True),
    sa.Column('on_campus_available', sa.Boolean(), nullable=True),
    sa.Column('eligibility_status', sa.Text(), nullable=False),
    sa.Column('eligibility_reason', sa.Text(), nullable=True),
    sa.Column('eligibility_confidence', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.Text(), nullable=False),
    sa.Column('approval_score', sa.Float(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_edited_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discovery_failure_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('diagnostic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_failure_alerts_university_id'), 'discovery_failure_alerts', ['university_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('university_name', sa.Text(), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('imported_rows', sa.Integer(), nullable=True),
    sa.Column('skipped_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_key')
    )
    op.create_table('scraping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('academic_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_level', sa.Text(), nullable=True),
    sa.Column('academic_score', sa.Float(), nullable=True),
    sa.Column('score_type', sa.Text(), nullable=True),
    sa.Column('academic_country', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('english_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.Text(), nullable=False),
    sa.Column('test_name', sa.Text(), nullable=True),
    sa.Column('listening', sa.Float(), nullable=True),
    sa.Column('speaking', sa.Float(), nullable=True),
    sa.Column('writing', sa.Float(), nullable=True),
    sa.Column('reading', sa.Float(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('international_fee', sa.Float(), nullable=True),
    sa.Column('fee_term', sa.Text(), nullable=True),
    sa.Column('fee_year', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('intake_month', sa.Text(), nullable=False),
    sa.Column('intake_day', sa.Integer(), nullable=True),
    sa.Column('intake_year', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_runtime_jobs',
    sa.Column('runtime_job_id', sa.Text(), nullable=False),
    sa.Column('scraping_job_id', sa.Integer(), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('university_name', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('discovered_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_decision', sa.Boolean(), nullable=True),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('fast_mode', sa.Boolean(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('total_found', sa.Integer(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('log_count', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=True),
    sa.Column('worker_pid', sa.Integer(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('requeue_count', sa.Integer(), nullable=False),
    sa.Column('requeue_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cost_ceiling_hit', sa.Boolean(), nullable=False),
    sa.Column('total_gemini_cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scraping_job_id'], ['scraping_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('runtime_job_id')
    )
    op.create_table('scraped_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_job_id', sa.Text(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('sub_category', sa.Text(), nullable=True),
    sa.Column('course_website', sa.Text(), nullable=True),
    sa.Column('duration', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_term', sa.Text(), nullable=True),
    sa.Column('study_mode', sa.Text(), nullable=True),
    sa.Column('degree_level', sa.Text(), nullable=True),
    sa.Column('study_load', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('other_requirement', sa.Text(), nullable=True),
    sa.Column('international_fee', sa.Float(), nullable=True),
    sa.Column('fee_term', sa.Text(), nullable=True),
    sa.Column('fee_year', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('ielts_overall', sa.Float(), nullable=True),
    sa.Column('ielts_listening', sa.Float(), nullable=True),
    sa.Column('ielts_speaking', sa.Float(), nullable=True),
    sa.Column('ielts_writing', sa.Float(), nullable=True),
    sa.Column('ielts_reading', sa.Float(), nullable=True),
    sa.Column('pte_overall', sa.Float(), nullable=True),
    sa.Column('pte_listening', sa.Float(), nullable=True),
    sa.Column('pte_speaking', sa.Float(), nullable=True),
    sa.Column('pte_writing', sa.Float(), nullable=True),
    sa.Column('pte_reading', sa.Float(), nullable=True),
    sa.Column('toefl_overall', sa.Float(), nullable=True),
    sa.Column('toefl_listening', sa.Float(), nullable=True),
    sa.Column('toefl_speaking', sa.Float(), nullable=True),
    sa.Column('toefl_writing', sa.Float(), nullable=True),
    sa.Column('toefl_reading', sa.Float(), nullable=True),
    sa.Column('cambridge_overall', sa.Float(), nullable=True),
    sa.Column('duolingo_overall', sa.Float(), nullable=True),
    sa.Column('duolingo_accepted', sa.Boolean(), nullable=True),
    sa.Column('cambridge_accepted', sa.Boolean(), nullable=True),
    sa.Column('pte_accepted', sa.Boolean(), nullable=True),
    sa.Column('toefl_accepted', sa.Boolean(), nullable=True),
    sa.Column('intake_months', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intake_days', sa.Integer(), nullable=True),
    sa.Column('academic_level', sa.Text(), nullable=True),
    sa.Column('academic_score', sa.Float(), nullable=True),
    sa.Column('score_type', sa.Text(), nullable=True),
    sa.Column('academic_country', sa.Text(), nullable=True),
    sa.Column('scholarship', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completeness', sa.Integer(), nullable=True),
    sa.Column('course_location', sa.Text(), nullable=True),
    sa.Column('student_market', sa.Text(), nullable=True),
    sa.Column('delivery_mode', sa.Text(), nullable=True),
    sa.Column('international_eligible', sa.Boolean(), nullable=True),
    sa.Column('on_campus_available', sa.Boolean(), nullable=True),
    sa.Column('eligibility_status', sa.Text(), nullable=False),
    sa.Column('eligibility_reason', sa.Text(), nullable=True),
    sa.Column('eligibility_confidence', sa.Float(), nullable=True),
    sa.Column('auto_publish_status', sa.Text(), nullable=False),
    sa.Column('decision_score', sa.Float(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('extraction_method', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scrape_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_central_fee_page', sa.Boolean(), nullable=False),
    sa.Column('cricos_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_key')
    )
    op.create_table('gemini_call_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scrape_run_id', sa.Text(), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('course_url', sa.Text(), nullable=True),
    sa.Column('call_type', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runtime_jobs.runtime_job_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gemini_call_log_scrape_run_id'), 'gemini_call_log', ['scrape_run_id'], unique=False)
    op.create_index(op.f('ix_gemini_call_log_university_id'), 'gemini_call_log', ['university_id'], unique=False)
    op.create_table('scrape_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('scraped_course_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.Text(), nullable=True),
    sa.Column('field_key', sa.Text(), nullable=True),
    sa.Column('issue_type', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('preferred_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scraped_course_id'], ['scraped_courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_run_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expected', sa.Numeric(), nullable=True),
    sa.Column('actual', sa.Numeric(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.Text(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runtime_jobs.runtime_job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_run_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Text(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('courses_total', sa.Integer(), nullable=False),
    sa.Column('fill_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runtime_jobs.runtime_job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrape_run_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Text(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('run_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_finished_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_duration_seconds', sa.Integer(), sa.Computed('EXTRACT(EPOCH FROM (run_finished_at - run_started_at))::int', persisted=True), nullable=True),
    sa.Column('candidates_discovered', sa.Integer(), nullable=False),
    sa.Column('candidates_staged', sa.Integer(), nullable=False),
    sa.Column('candidates_skipped', sa.Integer(), nullable=False),
    sa.Column('skipped_domestic_only', sa.Integer(), nullable=False),
    sa.Column('skipped_online_only', sa.Integer(), nullable=False),
    sa.Column('skipped_no_international_fee', sa.Integer(), nullable=False),
    sa.Column('skipped_category_landing_page', sa.Integer(), nullable=False),
    sa.Column('skipped_generic_category_page', sa.Integer(), nullable=False),
    sa.Column('skipped_fetch_failed', sa.Integer(), nullable=False),
    sa.Column('skipped_other', sa.Integer(), nullable=False),
    sa.Column('fill_rate_international_fee', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fill_rate_ielts_overall', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fill_rate_pte_overall', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fill_rate_toefl_overall', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fill_rate_duration', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fill_rate_intake_months', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fill_rate_course_location', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fill_rate_study_mode', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('fill_rate_cricos_code', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('method_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gemini_calls', sa.Integer(), nullable=False),
    sa.Column('gemini_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('avg_cost_per_course', sa.Numeric(precision=10, scale=6), sa.Computed('CASE WHEN candidates_staged > 0 THEN gemini_cost_usd / candidates_staged ELSE 0 END', persisted=True), nullable=True),
    sa.Column('fetch_errors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runtime_jobs.runtime_job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scrape_run_id')
    )
    op.create_table('scrape_runtime_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runtime_job_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['runtime_job_id'], ['scrape_runtime_jobs.runtime_job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_field_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_course_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('candidate_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('page_type', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision_score', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.Text(), nullable=False),
    sa.Column('decision_status', sa.Text(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scraped_course_id'], ['scraped_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scraped_course_id', 'field_key', 'extraction_method', 'source_url', name='scraped_field_evidence_dedup')
    )
    op.create_table('scraping_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraping_job_id', sa.Integer(), nullable=True),
    sa.Column('scraped_course_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('university_name', sa.Text(), nullable=True),
    sa.Column('course_name', sa.Text(), nullable=True),
    sa.Column('field_changed', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraped_course_id'], ['scraped_courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraping_job_id'], ['scraping_jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('scraped_course_id', sa.Integer(), nullable=True),
    sa.Column('source_evidence_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scraped_course_id'], ['scraped_courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['scraped_field_evidence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_field_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('final_value', sa.Text(), nullable=True),
    sa.Column('source_evidence_id', sa.Integer(), nullable=True),
    sa.Column('decision_score', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['scraped_field_evidence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_course_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('field_key', sa.Text(), nullable=False),
    sa.Column('value_a', sa.Text(), nullable=True),
    sa.Column('value_b', sa.Text(), nullable=True),
    sa.Column('evidence_a_id', sa.Integer(), nullable=True),
    sa.Column('evidence_b_id', sa.Integer(), nullable=True),
    sa.Column('conflict_type', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_a_id'], ['scraped_field_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_b_id'], ['scraped_field_evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scraped_course_id'], ['scraped_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_conflicts')
    op.drop_table('course_field_approvals')
    op.drop_table('course_audit_log')
    op.drop_table('scraping_changes')
    op.drop_table('scraped_field_evidence')
    op.drop_table('scrape_runtime_logs')
    op.drop_table('scrape_run_summary')
    op.drop_table('scrape_run_metrics')
    op.drop_table('scrape_run_alerts')
    op.drop_table('scrape_feedback')
    op.drop_index(op.f('ix_gemini_call_log_university_id'), table_name='gemini_call_log')
    op.drop_index(op.f('ix_gemini_call_log_scrape_run_id'), table_name='gemini_call_log')
    op.drop_table('gemini_call_log')
    op.drop_table('user_permissions')
    op.drop_table('scraped_courses')
    op.drop_table('scrape_runtime_jobs')
    op.drop_table('scholarships')
    op.drop_table('password_reset_tokens')
    op.drop_table('intakes')
    op.drop_table('fees')
    op.drop_table('english_requirements')
    op.drop_table('academic_requirements')
    op.drop_table('users')
    op.drop_table('scraping_jobs')
    op.drop_table('role_permissions')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_discovery_failure_alerts_university_id'), table_name='discovery_failure_alerts')
    op.drop_table('discovery_failure_alerts')
    op.drop_table('courses')
    op.drop_table('assessment_notes')
    op.drop_table('university_field_baselines')
    op.drop_table('universities')
    op.drop_table('scraper_config_history')
    op.drop_table('roles')
    op.drop_table('course_acronym_options')
    op.drop_table('central_page_cache')
    op.drop_table('bulk_sessions')
    op.drop_table('academic_level_options')
    # ### end Alembic commands ###
