"""AI Extraction Rule Runner — Phase 2 of the autonomous pipeline.

Applies per-field extraction rules generated by :mod:`ai_extractor_gen` to
a course HTML page.  This is **Stage 0** inside ``extract_course()`` — runs
before all regex heuristics and before any Gemini call.

When generated rules cover all 13 review fields, Gemini is never called for
that course, reducing per-course AI cost to zero.

Rule application order per field:
1. CSS selector  (via BeautifulSoup)
2. XPath         (via lxml — graceful fallback if lxml unavailable)
3. Regex         (applied to plain-text version of the page)

Transform post-processing:
- ``currency``   → strip "$", "AUD", ","; return float as string
- ``number``     → extract first integer/float
- ``list``       → split on commas/semicolons → Python list → JSON string
- ``month_list`` → normalise to 3-letter month codes, comma-separated string
"""
from __future__ import annotations

import logging
import re
from typing import Any

log = logging.getLogger(__name__)

# ── Month normalisation map ────────────────────────────────────────────────────
_MONTH_MAP: dict[str, int] = {
    "jan": 1, "feb": 2, "mar": 3, "apr": 4, "may": 5, "jun": 6,
    "jul": 7, "aug": 8, "sep": 9, "oct": 10, "nov": 11, "dec": 12,
    "january": 1, "february": 2, "march": 3, "april": 4, "june": 6,
    "july": 7, "august": 8, "september": 9, "october": 10,
    "november": 11, "december": 12,
}
_MONTH_NAMES = ["January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"]

# SoupSieve evaluates ancestor and sibling relations by walking back from
# every candidate element.  A generated selector with a long relation chain
# can therefore turn one ``select_one`` into a near-full-document search.  In
# particular, the SEGi Colleges rules generated a seven-level descendant
# selector and a 22-level direct-child selector.  Those selectors were valid
# CSS, but their evaluation on the ~600 KB WordPress document was effectively
# unbounded (the worker stayed at 100% CPU in
# ``soupsieve.match_past_relations``).
#
# Keep these limits specific to generated CSS rules.  A selector over either
# limit is skipped here and the existing XPath/regex fallback for the same
# rule is still attempted by ``apply_extraction_rules``.  This avoids changing
# extraction semantics for ordinary selectors, and avoids trying to interrupt
# SoupSieve after it has entered its synchronous matcher.
_MAX_GENERATED_CSS_DESCENDANT_RELATIONS = 7
_MAX_GENERATED_CSS_CHILD_RELATIONS = 16
_MAX_GENERATED_CSS_OTHER_RELATIONS = 7


def _css_selector_complexity(selector: str) -> tuple[int, int, int]:
    """Return ``(descendant, child, other)`` top-level CSS relations.

    This is intentionally a small lexical scan rather than a CSS parser.  It
    only needs to identify generated selectors whose relation chain is
    pathological, and scanning outside attribute/function contents avoids
    counting ``>`` or ``~`` characters in quoted values.  Comma-separated
    selector alternatives are counted together; a generated rule with one
    unusually deep alternative should be bounded just like a single selector.
    """
    descendant = 0
    child = 0
    other = 0
    bracket_depth = 0
    paren_depth = 0
    quote: str | None = None
    escaped = False
    pending_space = False
    explicit_relation = False

    for char in selector:
        if quote is not None:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == quote:
                quote = None
            continue

        if char in {"'", '"'} and (bracket_depth or paren_depth):
            quote = char
            continue
        if char == "[":
            bracket_depth += 1
            continue
        if char == "]" and bracket_depth:
            bracket_depth -= 1
            continue
        if char == "(":
            paren_depth += 1
            continue
        if char == ")" and paren_depth:
            paren_depth -= 1
            continue

        if bracket_depth or paren_depth:
            continue

        if char.isspace():
            pending_space = True
            continue

        if char in {">", "+", "~"}:
            if char == ">":
                child += 1
            else:
                other += 1
            pending_space = False
            explicit_relation = True
            continue

        # Whitespace between two compound selectors is a descendant
        # combinator.  Whitespace around an explicit combinator is not.
        if pending_space and not explicit_relation:
            descendant += 1
        pending_space = False
        explicit_relation = False

    return descendant, child, other


def _is_pathological_generated_css(selector: str) -> bool:
    """Return whether a generated selector must bypass SoupSieve.

    Generated rules are allowed to fall back to XPath/regex, so rejecting only
    this narrow shape is safer than adding a timeout around the whole
    extraction call.  A timeout cannot stop SoupSieve while it is executing
    synchronous Python on the worker's event loop.
    """
    descendant, child, other = _css_selector_complexity(selector)
    pathological = (
        descendant >= _MAX_GENERATED_CSS_DESCENDANT_RELATIONS
        or descendant + other >= _MAX_GENERATED_CSS_DESCENDANT_RELATIONS
        or child >= _MAX_GENERATED_CSS_CHILD_RELATIONS
        or other >= _MAX_GENERATED_CSS_OTHER_RELATIONS
    )
    if pathological:
        log.warning(
            "[EXTRACTOR_RUN] skipping pathological generated CSS selector "
            "(descendant=%d child=%d other=%d): %s",
            descendant,
            child,
            other,
            selector[:240],
        )
    return pathological


def _apply_transform(value: str, transform: str | None) -> str:
    """Post-process an extracted string according to the transform hint."""
    if not transform or not value:
        return value.strip()

    t = transform.lower()

    if t == "currency":
        # Strip currency symbols, commas, whitespace; return numeric string
        cleaned = re.sub(r"[^\d.]", "", value.replace(",", ""))
        return cleaned if cleaned else value.strip()

    if t == "number":
        m = re.search(r"(\d+(?:\.\d+)?)", value)
        return m.group(1) if m else value.strip()

    if t == "list":
        items = re.split(r"[;,]", value)
        return ",".join(i.strip() for i in items if i.strip())

    if t == "month_list":
        months: list[int] = []
        for word in re.findall(r"[A-Za-z]+", value):
            idx = _MONTH_MAP.get(word.lower())
            if idx and idx not in months:
                months.append(idx)
        months.sort()
        return ",".join(_MONTH_NAMES[m - 1] for m in months) if months else value.strip()

    return value.strip()


def _apply_css(soup: Any, selector: str, attribute: str | None) -> str | None:
    """Apply a CSS selector via BeautifulSoup; return text or attribute value.

    ``attribute="text"`` (or omitting attribute entirely) returns the element's
    inner text.  Any other attribute string is treated as an HTML attribute name
    (e.g. ``"href"``, ``"content"``, ``"data-value"``).
    """
    if not isinstance(selector, str):
        return None
    if _is_pathological_generated_css(selector):
        return None
    try:
        el = soup.select_one(selector)
        if el is None:
            return None
        if attribute and attribute.lower() != "text":
            val = el.get(attribute)
            return str(val).strip() if val else None
        return el.get_text(separator=" ").strip() or None
    except Exception as exc:
        log.debug("[EXTRACTOR_RUN] CSS selector %r failed: %s", selector, exc)
        return None


def _apply_xpath(html: str, expr: str, attribute: str | None) -> str | None:
    """Apply an XPath 1.0 expression via lxml; return text or attribute value."""
    try:
        from lxml import etree  # type: ignore[import-untyped]
        parser = etree.HTMLParser()
        tree = etree.fromstring(html.encode(), parser)
        results = tree.xpath(expr)
        if not results:
            return None
        first = results[0]
        if attribute and attribute.lower() != "text":
            val = first.get(attribute) if hasattr(first, "get") else None
            return val.strip() if val else None
        if hasattr(first, "text_content"):
            return first.text_content().strip() or None
        if hasattr(first, "itertext"):
            return " ".join(first.itertext()).strip() or None
        return str(first).strip() or None
    except Exception as exc:
        log.debug("[EXTRACTOR_RUN] XPath %r failed: %s", expr, exc)
        return None


def _apply_regex(page_text: str, pattern: str) -> str | None:
    """Apply a regex with one capture group to the plain-text version of the page."""
    try:
        m = re.search(pattern, page_text, re.I | re.S)
        if m:
            return m.group(1).strip() if m.lastindex else m.group(0).strip()
        return None
    except re.error as exc:
        log.debug("[EXTRACTOR_RUN] Regex %r error: %s", pattern, exc)
        return None


def _html_to_text(html: str) -> str:
    """Fast HTML → plain text for regex matching."""
    text = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", html, flags=re.S | re.I)
    text = re.sub(r"<[^>]+>", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def apply_extraction_rules(
    html: str,
    rules: dict[str, dict[str, Any]],
) -> dict[str, tuple[str | None, str]]:
    """Apply generated extraction rules to a course HTML page.

    Parameters
    ----------
    html:
        Raw HTML of the course detail page.
    rules:
        Per-field rule dicts from ``auto_config["extraction_rules"]``.

    Returns
    -------
    dict mapping field_name → (extracted_value_or_None, method_string).
    ``method_string`` follows the convention used in ``scraped_field_evidence``:
    ``"ai_rule:css"``, ``"ai_rule:xpath"``, or ``"ai_rule:regex"``.
    Empty value → ``(None, "ai_rule:miss")``.
    """
    if not html or not rules:
        return {}

    from bs4 import BeautifulSoup  # type: ignore[import-untyped]

    soup = BeautifulSoup(html, "html.parser")
    page_text = _html_to_text(html)

    results: dict[str, tuple[str | None, str]] = {}

    for field, rule in rules.items():
        if not isinstance(rule, dict):
            continue

        css = rule.get("css") or ""
        xpath = rule.get("xpath") or ""
        regex = rule.get("regex") or ""
        attr = rule.get("attribute") or None
        transform = rule.get("transform") or None

        raw: str | None = None
        method = "ai_rule:miss"

        if css:
            raw = _apply_css(soup, css, attr)
            if raw is not None:
                method = "ai_rule:css"

        if raw is None and xpath:
            raw = _apply_xpath(html, xpath, attr)
            if raw is not None:
                method = "ai_rule:xpath"

        if raw is None and regex:
            raw = _apply_regex(page_text, regex)
            if raw is not None:
                method = "ai_rule:regex"

        if raw is not None:
            raw = _apply_transform(raw, transform)

        results[field] = (raw or None, method)

    filled = sum(1 for v, _ in results.values() if v is not None)
    log.debug(
        "[EXTRACTOR_RUN] %d/%d rules fired (fields: %s)",
        filled, len(rules),
        [f for f, (v, _) in results.items() if v is not None],
    )
    return results


def should_skip_gemini(
    results: dict[str, tuple[str | None, str]],
    review_fields: list[str],
    min_coverage: float = 0.85,
) -> bool:
    """Return True if rule coverage is high enough to skip Gemini entirely.

    Parameters
    ----------
    results:
        Output of :func:`apply_extraction_rules`.
    review_fields:
        The 13 canonical review fields from completeness.py.
    min_coverage:
        Fraction of review fields that must be filled to skip Gemini.
        Default 0.85 (85 %) — same as the auto-publish completeness floor.
    """
    if not results or not review_fields:
        return False
    filled = sum(
        1 for f in review_fields
        if results.get(f, (None, ""))[0] is not None
    )
    coverage = filled / len(review_fields)
    skip = coverage >= min_coverage
    if skip:
        log.info(
            "[EXTRACTOR_RUN] Coverage %.0f%% ≥ %.0f%% — Gemini will be skipped for this course",
            coverage * 100, min_coverage * 100,
        )
    return skip
