import { pgTable, text, serial, timestamp, integer, real, jsonb, boolean } from "drizzle-orm/pg-core";
import { universitiesTable } from "./universities";
import { coursesTable } from "./courses";

export const scrapedCoursesTable = pgTable("scraped_courses", {
  id: serial("id").primaryKey(),
  scrapeJobId: text("scrape_job_id").notNull(),
  universityId: integer("university_id").notNull().references(() => universitiesTable.id, { onDelete: "cascade" }),
  courseName: text("course_name").notNull(),
  category: text("category"),
  subCategory: text("sub_category"),
  courseWebsite: text("course_website"),
  courseLocation: text("course_location"),
  duration: real("duration"),
  durationTerm: text("duration_term"),
  studyMode: text("study_mode"),
  degreeLevel: text("degree_level"),
  studyLoad: text("study_load"),
  language: text("language"),
  description: text("description"),
  otherRequirement: text("other_requirement"),
  internationalFee: real("international_fee"),
  feeTerm: text("fee_term"),
  feeYear: integer("fee_year"),
  currency: text("currency"),
  ieltsOverall: real("ielts_overall"),
  ieltsListening: real("ielts_listening"),
  ieltsSpeaking: real("ielts_speaking"),
  ieltsWriting: real("ielts_writing"),
  ieltsReading: real("ielts_reading"),
  pteOverall: real("pte_overall"),
  pteListening: real("pte_listening"),
  pteSpeaking: real("pte_speaking"),
  pteWriting: real("pte_writing"),
  pteReading: real("pte_reading"),
  toeflOverall: real("toefl_overall"),
  toeflListening: real("toefl_listening"),
  toeflSpeaking: real("toefl_speaking"),
  toeflWriting: real("toefl_writing"),
  toeflReading: real("toefl_reading"),
  cambridgeOverall: real("cambridge_overall"),
  duolingoOverall: real("duolingo_overall"),
  intakeMonths: jsonb("intake_months").$type<string[]>(),
  intakeDays: integer("intake_days"),
  academicLevel: text("academic_level"),
  academicScore: real("academic_score"),
  scoreType: text("score_type"),
  academicCountry: text("academic_country"),
  scholarship: text("scholarship"),
  studentMarket: text("student_market"),
  deliveryMode: text("delivery_mode"),
  internationalEligible: boolean("international_eligible"),
  onCampusAvailable: boolean("on_campus_available"),
  eligibilityStatus: text("eligibility_status").notNull().default("unknown"),
  eligibilityReason: text("eligibility_reason"),
  eligibilityConfidence: real("eligibility_confidence"),
  autoPublishStatus: text("auto_publish_status").notNull().default("pending_review"),
  decisionScore: real("decision_score"),
  status: text("status").notNull().default("pending"),
  courseId: integer("course_id").references(() => coursesTable.id, { onDelete: "set null" }),
  notes: text("notes"),
  completeness: integer("completeness"),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export type ScrapedCourse = typeof scrapedCoursesTable.$inferSelect;
