"""Load and merge per-university scraper configuration.

Priority chain (lowest → highest):
  1. Built-in Pydantic defaults (schema.py field defaults)
  2. ``scraper_config/defaults.yaml``            — conservative global defaults
  3. DB ``university.scrape_config.uniPages``    — backwards-compat manual UI config
  4. DB ``university.scrape_config.auto_config`` — auto-generated by site probe (NEW)
  5. ``scraper_config/unis/<slug>.yaml``          — per-university YAML (emergency override)

The loader is intentionally synchronous: it is called once per scrape job
at worker startup, before any async I/O.  Results are NOT cached at the
module level so that config file changes take effect on the next scrape
without requiring a worker restart.  If the startup cost becomes measurable
(unlikely given ~20 YAML files), add an LRU cache keyed on (slug, mtime).

Slug derivation
---------------
The slug is derived from the primary hostname of the university's scrape URL:

  www.acu.edu.au  →  acu
  www.aut.ac.nz   →  aut
  bond.edu.au     →  bond

The per-university YAML file is looked up at ``unis/<slug>.yaml``.  If no
file exists for that slug the loader falls back to a config built from
defaults only (plus the DB scrape_config backwards-compat translation).
"""
from __future__ import annotations

import logging
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import yaml

from app.services.scraper.config.schema import UniConfig

log = logging.getLogger(__name__)

_CONFIGS_ROOT = Path(__file__).parent.parent.parent.parent.parent / "scraper_config"
_DEFAULTS_FILE = _CONFIGS_ROOT / "defaults.yaml"
_UNIS_DIR = _CONFIGS_ROOT / "unis"

# Common TLD-style tokens that should not become the slug.
_TLD_TOKENS: frozenset[str] = frozenset(
    {"edu", "ac", "com", "net", "org", "gov", "au", "nz", "uk", "us", "ca"}
)

# Generic subdomain prefixes that do NOT represent an institution name.
# These are stripped before picking the slug token so that e.g.
# ``study.csu.edu.au`` → ``csu`` and ``courses.hud.ac.uk`` → ``hud``.
_GENERIC_SUBDOMAINS: frozenset[str] = frozenset({
    "www", "study", "international", "courses", "handbook",
    "programs", "programsandcourses", "apply", "admissions",
    "portal", "student", "students", "my", "secure", "web",
    "info", "find", "explore", "future", "search",
})

# Keys injected by auto_config_generator that are metadata, not config fields.
# Strip these before merging into UniConfig to avoid Pydantic validation errors.
_AUTO_CONFIG_META_KEYS: frozenset[str] = frozenset(
    {"_auto_generated", "_strategy", "_probe_summary", "_api_provider",
     "_api_endpoint_hint", "_blocked", "_notes"}
)


def _hostname_to_slug(hostname: str) -> str:
    """Derive a short slug from a hostname.

    Strips leading generic subdomain prefixes (www, study, international, …)
    then returns the first label that is not a TLD token.

    >>> _hostname_to_slug("www.acu.edu.au")
    'acu'
    >>> _hostname_to_slug("www.aut.ac.nz")
    'aut'
    >>> _hostname_to_slug("bond.edu.au")
    'bond'
    >>> _hostname_to_slug("www.uow.edu.au")
    'uow'
    >>> _hostname_to_slug("study.csu.edu.au")
    'csu'
    >>> _hostname_to_slug("courses.hud.ac.uk")
    'hud'
    >>> _hostname_to_slug("international.uts.edu.au")
    'uts'
    """
    parts = hostname.lower().split(".")
    # Strip leading generic subdomain labels (keep at least 2 parts).
    while len(parts) > 2 and parts[0] in _GENERIC_SUBDOMAINS:
        parts = parts[1:]
    for part in parts:
        if part not in _TLD_TOKENS:
            return part
    return parts[0]


def _infer_currency(hostname: str) -> str:
    """Return the most likely fee currency for a university hostname."""
    h = hostname.lower()
    if h.endswith(".ac.uk") or h.endswith(".co.uk") or h.endswith(".uk"):
        return "GBP"
    if h.endswith(".ac.nz") or h.endswith(".co.nz") or h.endswith(".nz"):
        return "NZD"
    if h.endswith(".ca"):
        return "CAD"
    if h.endswith(".ie"):
        return "EUR"
    if h.endswith(".us") or h.endswith(".edu"):
        return "USD"
    return "AUD"  # .edu.au, .com.au, unknown → AUD default


def _infer_country(hostname: str) -> str:
    """Return a display country name from a university hostname."""
    h = hostname.lower()
    if h.endswith(".uk"):
        return "United Kingdom"
    if h.endswith(".nz"):
        return "New Zealand"
    if h.endswith(".ca"):
        return "Canada"
    if h.endswith(".ie"):
        return "Ireland"
    if h.endswith(".us") or h.endswith(".edu"):
        return "United States"
    return "Australia"


def _create_stub_yaml(
    *,
    slug: str,
    name: str,
    scrape_url: str,
    hostname: str,
    university_id: int | None,
) -> Path:
    """Write a minimal stub YAML for a university with no existing config file.

    Uses an id-specific filename (``{slug}_{university_id}.yaml``) when
    ``university_id`` is known so that future slug collisions are avoided
    automatically.  Falls back to ``{slug}.yaml`` when id is unavailable.

    The stub is intentionally minimal — it sets only ``default_currency``
    (inferred from the hostname TLD) so the scraper doesn't misclassify
    GBP/NZD fees as AUD.  Operators can expand it after the first run.
    """
    if path := (_UNIS_DIR / f"{slug}_{university_id}.yaml") if university_id else None:
        target = path
    else:
        target = _UNIS_DIR / f"{slug}.yaml"

    if target.exists():
        return target

    currency = _infer_currency(hostname)
    country = _infer_country(hostname)
    today = date.today().isoformat()

    content = (
        f"# {name}\n"
        f"# Hostname: {hostname}\n"
        f"# Country: {country}  |  Currency: {currency}\n"
        f"# Slug: {slug}\n"
        f"# Auto-generated: {today}\n"
        "#\n"
        "# This stub was created automatically on the first scrape of this university.\n"
        "# Review and expand it to improve discovery and extraction quality.\n"
        "# See scraper_config/defaults.yaml for all available options.\n"
        "\n"
        "discovery: {}\n"
        "\n"
        "extraction:\n"
        "  fees:\n"
        f"    default_currency: {currency}\n"
    )

    try:
        _UNIS_DIR.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        log.info(
            "Auto-created stub YAML for slug=%r uni_id=%r → %s (currency=%s country=%s)",
            slug,
            university_id,
            target.name,
            currency,
            country,
        )
    except OSError as exc:
        log.warning("Could not write stub YAML for slug=%r: %s", slug, exc)

    return target


def _load_yaml_file(path: Path) -> dict[str, Any]:
    """Load a YAML file and return its contents as a dict.  Returns {} on error."""
    try:
        with path.open(encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
            return data if isinstance(data, dict) else {}
    except FileNotFoundError:
        return {}
    except yaml.YAMLError as exc:
        log.error("YAML parse error in %s: %s", path, exc)
        return {}


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge *override* into *base*.  Override wins on conflicts.

    Special rule for list-type config fields (allow_url_patterns,
    block_url_patterns, must_contain, seed_urls, …): an empty list ``[]``
    in *override* is treated as "no opinion / not set" and does NOT clear a
    non-empty list already present in *base*.  This prevents the admin UI
    from accidentally wiping YAML-defined URL patterns when the operator
    saves a form that happens to serialize an empty list for those fields.
    A non-empty list in *override* always wins as usual.
    """
    _LIST_NO_CLEAR_KEYS: frozenset[str] = frozenset({
        "allow_url_patterns", "block_url_patterns", "must_contain",
        "seed_urls", "block_nav_patterns", "fallback_subdomains",
    })
    result: dict[str, Any] = dict(base)
    for key, val in override.items():
        if val is None:
            # Explicit None in override → skip (treat as "unset")
            continue
        if (
            key in _LIST_NO_CLEAR_KEYS
            and isinstance(val, list)
            and len(val) == 0
            and isinstance(result.get(key), list)
            and len(result[key]) > 0
        ):
            # Empty list override must not clear an existing non-empty list
            continue
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def _translate_db_scrape_config(db_cfg: dict[str, Any]) -> dict[str, Any]:
    """Translate the legacy DB ``university.scrape_config`` JSONB into the new schema.

    The existing ``uniPages`` keys in the DB are the source-of-truth for
    central-page URLs that have been manually configured through the Admin UI.
    We translate them into the new ``extraction.fees`` / ``extraction.english``
    structure so that the UniConfig reflects the full picture.

    Precedence: per-uni YAML > auto_config > DB scrape_config.  The caller
    applies the DB translation BEFORE both auto_config and the per-uni YAML.

    This translation is READ-ONLY — it never modifies the DB.
    """
    uni_pages: dict[str, str] = db_cfg.get("uniPages") or {}
    translated: dict[str, Any] = {}

    fees_central = uni_pages.get("feePage") or uni_pages.get("feesPage")
    fees_pdf = uni_pages.get("feesPdf")
    if fees_central:
        translated.setdefault("extraction", {}).setdefault("fees", {})["central_page"] = (
            fees_central
        )
    if fees_pdf:
        translated.setdefault("extraction", {}).setdefault("fees", {})["fees_pdf_url"] = (
            fees_pdf
        )

    english_page = (
        uni_pages.get("entryPage")
        or uni_pages.get("requirementsPage")
        or uni_pages.get("englishPage")
    )
    english_pdf = uni_pages.get("requirementsPdf")
    if english_page:
        translated.setdefault("extraction", {}).setdefault("english", {})["central_page"] = (
            english_page
        )
    if english_pdf:
        translated.setdefault("extraction", {}).setdefault("english", {})[
            "requirements_pdf_url"
        ] = english_pdf

    return translated


def _extract_auto_config(db_cfg: dict[str, Any]) -> dict[str, Any]:
    """Extract the auto-generated probe config from DB scrape_config.

    The probe stores its output under ``scrape_config["auto_config"]``.
    Strip internal metadata keys (prefixed with ``_``) before merging so
    Pydantic validation isn't confused by non-schema keys.
    """
    auto_cfg = db_cfg.get("auto_config")
    if not auto_cfg or not isinstance(auto_cfg, dict):
        return {}
    return {k: v for k, v in auto_cfg.items() if k not in _AUTO_CONFIG_META_KEYS}


def _extract_admin_config(db_cfg: dict[str, Any]) -> dict[str, Any]:
    """Extract the admin UI-written config from DB scrape_config.

    Written by the portal's Scrape Fix Agent under ``scrape_config["admin_config"]``.
    Priority: above auto_config (probe), below per-uni YAML (emergency override).

    Keys starting with ``_`` are metadata-only (e.g. ``_min_expected_courses``)
    and are stripped before passing to Pydantic to avoid validation errors.
    """
    admin_cfg = db_cfg.get("admin_config")
    if not admin_cfg or not isinstance(admin_cfg, dict):
        return {}
    return {k: v for k, v in admin_cfg.items() if not k.startswith("_")}


def load_uni_config(
    *,
    slug: str,
    name: str,
    scrape_url: str,
    base_url: str = "",
    university_id: int | None = None,
    db_scrape_config: dict[str, Any] | None = None,
) -> UniConfig:
    """Build a fully-merged UniConfig for one university.

    Parameters
    ----------
    slug:
        Short identifier for the university (e.g. ``"acu"``).  Used to look
        up ``scraper_config/unis/<slug>.yaml``.
    name:
        Human-readable name (e.g. ``"Australian Catholic University"``).
    scrape_url:
        Discovery entry-point URL (e.g. ``"https://www.acu.edu.au/courses"``).
    base_url:
        Origin URL.  If omitted, derived from ``scrape_url``.
    university_id:
        DB primary key.  Stored in the config for logging only.
    db_scrape_config:
        Contents of ``university.scrape_config`` from the DB.  Contains both
        the legacy ``uniPages`` manual config AND the auto-generated
        ``auto_config`` block written by the site probe.
    """
    if not base_url:
        parsed = urlparse(scrape_url)
        base_url = f"{parsed.scheme}://{parsed.netloc}" if parsed.netloc else scrape_url

    # 1. Load defaults.yaml
    merged: dict[str, Any] = _load_yaml_file(_DEFAULTS_FILE)

    if db_scrape_config:
        # 2. Translate legacy DB uniPages → new schema (backwards compat)
        db_translated = _translate_db_scrape_config(db_scrape_config)
        if db_translated:
            merged = _deep_merge(merged, db_translated)

        # 3. Merge auto-generated probe config (higher priority than manual uniPages)
        auto_cfg = _extract_auto_config(db_scrape_config)
        if auto_cfg:
            merged = _deep_merge(merged, auto_cfg)
            log.debug(
                "Auto-config applied for slug=%r strategy=%r",
                slug,
                db_scrape_config.get("auto_config", {}).get("_strategy", "unknown"),
            )

    # 4. Load and merge per-uni YAML (developer baseline / emergency guardrails)
    #
    # Lookup order (most-specific wins):
    #   1. unis/{slug}_{university_id}.yaml — disambiguates two unis that share
    #      a slug (e.g. Torrens main campus and a Torrens network partner both
    #      resolve to "torrens").  Create this file when per-id overrides are
    #      needed; it shadows the shared slug file entirely.
    #   2. unis/{slug}.yaml — legacy / single-tenant case; used when the
    #      university_id-specific file does not exist.
    _id_yaml: Path | None = None
    if university_id is not None:
        candidate = _UNIS_DIR / f"{slug}_{university_id}.yaml"
        if candidate.exists():
            _id_yaml = candidate

    uni_yaml_path: Path = _id_yaml if _id_yaml is not None else _UNIS_DIR / f"{slug}.yaml"
    per_uni = _load_yaml_file(uni_yaml_path)
    if per_uni:
        # Hostname guard — prevents a shared-slug YAML from being applied to the
        # wrong university.  If the YAML declares ``hostname_guard: "www.foo.ac.nz"``
        # and the current scrape URL's hostname differs, the YAML is silently skipped
        # and the university falls back to defaults + DB config.
        #
        # This guards against slug collisions such as:
        #   www.canterbury.ac.uk  →  slug "canterbury"
        #   www.canterbury.ac.nz  →  slug "canterbury"
        # where both resolve to the same YAML file.  The id-specific filename
        # (e.g. canterbury_1750.yaml) is the PRIMARY disambiguation mechanism;
        # hostname_guard is a defence-in-depth safety net for shared slug files.
        _guard_host = per_uni.pop("hostname_guard", None)
        if _guard_host is not None:
            _scrape_host = urlparse(scrape_url).hostname or ""
            _guard_clean = _guard_host.lstrip("*.").lower()
            _scrape_clean = _scrape_host.lower()
            # Allow exact match OR subdomain-of-guard (e.g. guard="canterbury.ac.nz"
            # accepts "www.canterbury.ac.nz").
            _host_ok = (
                _scrape_clean == _guard_clean
                or _scrape_clean.endswith("." + _guard_clean)
            )
            if not _host_ok:
                log.warning(
                    "YAML hostname_guard mismatch for slug=%r: guard=%r scrape_host=%r "
                    "— skipping YAML (university will use defaults + DB config). "
                    "If this YAML should apply, update hostname_guard or create an "
                    "id-specific file (%s_%s.yaml).",
                    slug,
                    _guard_host,
                    _scrape_host,
                    slug,
                    university_id,
                )
                per_uni = {}

        if per_uni:
            if _id_yaml is not None:
                log.debug(
                    "Per-uni YAML loaded for slug=%r uni_id=%r (id-specific file)",
                    slug,
                    university_id,
                )
            merged = _deep_merge(merged, per_uni)
    else:
        # No hand-authored YAML exists yet — auto-create a minimal stub so:
        #   1. The correct fee currency (GBP/NZD/CAD/AUD) is set immediately,
        #      preventing false "possible_domestic_fee" data-quality flags.
        #   2. Operators have a starting file to expand after the first scrape.
        _parsed_host = urlparse(scrape_url).hostname or ""
        _stub_path = _create_stub_yaml(
            slug=slug,
            name=name,
            scrape_url=scrape_url,
            hostname=_parsed_host,
            university_id=university_id,
        )
        _stub_data = _load_yaml_file(_stub_path)
        if _stub_data:
            merged = _deep_merge(merged, _stub_data)

    if db_scrape_config:
        # 4.5. Merge admin UI config LAST so operator UI changes always win.
        #
        #      Priority: HIGHEST — above the per-uni YAML.
        #
        #      Rationale: the YAML is a developer-authored baseline that sets
        #      safe defaults for universities with known quirks.  The admin UI
        #      (Scrape Fix Agent "Apply AI Fix" / manual config panel) is how
        #      operators tune discovery without a code deploy.  If YAML won,
        #      every UI change would be silently discarded — the operator would
        #      see "Config applied" but nothing would actually change.
        #
        #      The YAML remains the right place for deep structural guardrails
        #      (block_nav_patterns, must_contain rules, always_browser_discover)
        #      that the UI doesn't surface; those are untouched unless the
        #      operator explicitly adds the same keys via the panel.
        admin_cfg = _extract_admin_config(db_scrape_config)
        if admin_cfg:
            merged = _deep_merge(merged, admin_cfg)
            log.debug("Admin UI config applied for slug=%r (highest priority)", slug)

    # 5. Inject identity fields (these are not in YAML, they come from the DB row)
    merged.pop("slug", None)
    merged.pop("name", None)
    merged.pop("university_id", None)
    merged.pop("base_url", None)
    merged.pop("scrape_url", None)

    try:
        return UniConfig(
            slug=slug,
            name=name,
            university_id=university_id,
            base_url=base_url,
            scrape_url=scrape_url,
            **merged,
        )
    except Exception as exc:
        log.error(
            "Failed to build UniConfig for slug=%r: %s — falling back to bare defaults",
            slug,
            exc,
        )
        return UniConfig(
            slug=slug,
            name=name,
            university_id=university_id,
            base_url=base_url,
            scrape_url=scrape_url,
        )


def get_config_for_host(
    *,
    hostname: str,
    name: str,
    scrape_url: str,
    university_id: int | None = None,
    db_scrape_config: dict[str, Any] | None = None,
) -> UniConfig:
    """Convenience wrapper: derive slug from hostname then call ``load_uni_config``."""
    slug = _hostname_to_slug(hostname)
    return load_uni_config(
        slug=slug,
        name=name,
        scrape_url=scrape_url,
        university_id=university_id,
        db_scrape_config=db_scrape_config,
    )
