"""Load and merge per-university scraper configuration.

Priority chain (lowest → highest):
  1. Built-in Pydantic defaults (schema.py field defaults)
  2. ``scraper_config/defaults.yaml``            — conservative global defaults
  3. DB ``university.scrape_config.uniPages``    — backwards-compat manual UI config
  4. DB ``university.scrape_config.auto_config`` — auto-generated by site probe (NEW)
  5. ``scraper_config/unis/<slug>.yaml``          — per-university YAML (emergency override)

The loader is intentionally synchronous: it is called once per scrape job
at worker startup, before any async I/O.  Results are NOT cached at the
module level so that config file changes take effect on the next scrape
without requiring a worker restart.  If the startup cost becomes measurable
(unlikely given ~20 YAML files), add an LRU cache keyed on (slug, mtime).

Slug derivation
---------------
The slug is derived from the primary hostname of the university's scrape URL:

  www.acu.edu.au  →  acu
  www.aut.ac.nz   →  aut
  bond.edu.au     →  bond

The per-university YAML file is looked up at ``unis/<slug>.yaml``.  If no
file exists for that slug the loader falls back to a config built from
defaults only (plus the DB scrape_config backwards-compat translation).
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import yaml

from app.services.scraper.config.schema import UniConfig

log = logging.getLogger(__name__)

_CONFIGS_ROOT = Path(__file__).parent.parent.parent.parent.parent / "scraper_config"
_DEFAULTS_FILE = _CONFIGS_ROOT / "defaults.yaml"
_UNIS_DIR = _CONFIGS_ROOT / "unis"

# Common TLD-style tokens that should not become the slug.
_TLD_TOKENS: frozenset[str] = frozenset(
    {"edu", "ac", "com", "net", "org", "gov", "au", "nz", "uk", "us", "ca"}
)

# Generic subdomain prefixes that do NOT represent an institution name.
# These are stripped before picking the slug token so that e.g.
# ``study.csu.edu.au`` → ``csu`` and ``courses.hud.ac.uk`` → ``hud``.
_GENERIC_SUBDOMAINS: frozenset[str] = frozenset({
    "www", "study", "international", "courses", "handbook",
    "programs", "programsandcourses", "apply", "admissions",
    "portal", "student", "students", "my", "secure", "web",
    "info", "find", "explore", "future", "search",
})

# Keys injected by auto_config_generator that are metadata, not config fields.
# Strip these before merging into UniConfig to avoid Pydantic validation errors.
_AUTO_CONFIG_META_KEYS: frozenset[str] = frozenset(
    {"_auto_generated", "_strategy", "_probe_summary", "_api_provider",
     "_api_endpoint_hint", "_blocked", "_notes"}
)


def _hostname_to_slug(hostname: str) -> str:
    """Derive a short slug from a hostname.

    Strips leading generic subdomain prefixes (www, study, international, …)
    then returns the first label that is not a TLD token.

    >>> _hostname_to_slug("www.acu.edu.au")
    'acu'
    >>> _hostname_to_slug("www.aut.ac.nz")
    'aut'
    >>> _hostname_to_slug("bond.edu.au")
    'bond'
    >>> _hostname_to_slug("www.uow.edu.au")
    'uow'
    >>> _hostname_to_slug("study.csu.edu.au")
    'csu'
    >>> _hostname_to_slug("courses.hud.ac.uk")
    'hud'
    >>> _hostname_to_slug("international.uts.edu.au")
    'uts'
    """
    parts = hostname.lower().split(".")
    # Strip leading generic subdomain labels (keep at least 2 parts).
    while len(parts) > 2 and parts[0] in _GENERIC_SUBDOMAINS:
        parts = parts[1:]
    for part in parts:
        if part not in _TLD_TOKENS:
            return part
    return parts[0]


def _load_yaml_file(path: Path) -> dict[str, Any]:
    """Load a YAML file and return its contents as a dict.  Returns {} on error."""
    try:
        with path.open(encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
            return data if isinstance(data, dict) else {}
    except FileNotFoundError:
        return {}
    except yaml.YAMLError as exc:
        log.error("YAML parse error in %s: %s", path, exc)
        return {}


def _deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge *override* into *base*.  Override wins on conflicts."""
    result: dict[str, Any] = dict(base)
    for key, val in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = _deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def _translate_db_scrape_config(db_cfg: dict[str, Any]) -> dict[str, Any]:
    """Translate the legacy DB ``university.scrape_config`` JSONB into the new schema.

    The existing ``uniPages`` keys in the DB are the source-of-truth for
    central-page URLs that have been manually configured through the Admin UI.
    We translate them into the new ``extraction.fees`` / ``extraction.english``
    structure so that the UniConfig reflects the full picture.

    Precedence: per-uni YAML > auto_config > DB scrape_config.  The caller
    applies the DB translation BEFORE both auto_config and the per-uni YAML.

    This translation is READ-ONLY — it never modifies the DB.
    """
    uni_pages: dict[str, str] = db_cfg.get("uniPages") or {}
    translated: dict[str, Any] = {}

    fees_central = uni_pages.get("feePage") or uni_pages.get("feesPage")
    fees_pdf = uni_pages.get("feesPdf")
    if fees_central:
        translated.setdefault("extraction", {}).setdefault("fees", {})["central_page"] = (
            fees_central
        )
    if fees_pdf:
        translated.setdefault("extraction", {}).setdefault("fees", {})["fees_pdf_url"] = (
            fees_pdf
        )

    english_page = (
        uni_pages.get("entryPage")
        or uni_pages.get("requirementsPage")
        or uni_pages.get("englishPage")
    )
    english_pdf = uni_pages.get("requirementsPdf")
    if english_page:
        translated.setdefault("extraction", {}).setdefault("english", {})["central_page"] = (
            english_page
        )
    if english_pdf:
        translated.setdefault("extraction", {}).setdefault("english", {})[
            "requirements_pdf_url"
        ] = english_pdf

    return translated


def _extract_auto_config(db_cfg: dict[str, Any]) -> dict[str, Any]:
    """Extract the auto-generated probe config from DB scrape_config.

    The probe stores its output under ``scrape_config["auto_config"]``.
    Strip internal metadata keys (prefixed with ``_``) before merging so
    Pydantic validation isn't confused by non-schema keys.
    """
    auto_cfg = db_cfg.get("auto_config")
    if not auto_cfg or not isinstance(auto_cfg, dict):
        return {}
    return {k: v for k, v in auto_cfg.items() if k not in _AUTO_CONFIG_META_KEYS}


def load_uni_config(
    *,
    slug: str,
    name: str,
    scrape_url: str,
    base_url: str = "",
    university_id: int | None = None,
    db_scrape_config: dict[str, Any] | None = None,
) -> UniConfig:
    """Build a fully-merged UniConfig for one university.

    Parameters
    ----------
    slug:
        Short identifier for the university (e.g. ``"acu"``).  Used to look
        up ``scraper_config/unis/<slug>.yaml``.
    name:
        Human-readable name (e.g. ``"Australian Catholic University"``).
    scrape_url:
        Discovery entry-point URL (e.g. ``"https://www.acu.edu.au/courses"``).
    base_url:
        Origin URL.  If omitted, derived from ``scrape_url``.
    university_id:
        DB primary key.  Stored in the config for logging only.
    db_scrape_config:
        Contents of ``university.scrape_config`` from the DB.  Contains both
        the legacy ``uniPages`` manual config AND the auto-generated
        ``auto_config`` block written by the site probe.
    """
    if not base_url:
        parsed = urlparse(scrape_url)
        base_url = f"{parsed.scheme}://{parsed.netloc}" if parsed.netloc else scrape_url

    # 1. Load defaults.yaml
    merged: dict[str, Any] = _load_yaml_file(_DEFAULTS_FILE)

    if db_scrape_config:
        # 2. Translate legacy DB uniPages → new schema (backwards compat)
        db_translated = _translate_db_scrape_config(db_scrape_config)
        if db_translated:
            merged = _deep_merge(merged, db_translated)

        # 3. Merge auto-generated probe config (higher priority than manual uniPages)
        auto_cfg = _extract_auto_config(db_scrape_config)
        if auto_cfg:
            merged = _deep_merge(merged, auto_cfg)
            log.debug(
                "Auto-config applied for slug=%r strategy=%r",
                slug,
                db_scrape_config.get("auto_config", {}).get("_strategy", "unknown"),
            )

    # 4. Load and merge per-uni YAML (highest priority — emergency override only)
    #
    # Lookup order (most-specific wins):
    #   1. unis/{slug}_{university_id}.yaml — disambiguates two unis that share
    #      a slug (e.g. Torrens main campus and a Torrens network partner both
    #      resolve to "torrens").  Create this file when per-id overrides are
    #      needed; it shadows the shared slug file entirely.
    #   2. unis/{slug}.yaml — legacy / single-tenant case; used when the
    #      university_id-specific file does not exist.
    _id_yaml: Path | None = None
    if university_id is not None:
        candidate = _UNIS_DIR / f"{slug}_{university_id}.yaml"
        if candidate.exists():
            _id_yaml = candidate

    uni_yaml_path: Path = _id_yaml if _id_yaml is not None else _UNIS_DIR / f"{slug}.yaml"
    per_uni = _load_yaml_file(uni_yaml_path)
    if per_uni:
        if _id_yaml is not None:
            log.debug(
                "Per-uni YAML loaded for slug=%r uni_id=%r (id-specific file)",
                slug,
                university_id,
            )
        merged = _deep_merge(merged, per_uni)
    else:
        log.debug("No per-uni YAML for slug=%r (will use defaults + DB config)", slug)

    # 5. Inject identity fields (these are not in YAML, they come from the DB row)
    merged.pop("slug", None)
    merged.pop("name", None)
    merged.pop("university_id", None)
    merged.pop("base_url", None)
    merged.pop("scrape_url", None)

    try:
        return UniConfig(
            slug=slug,
            name=name,
            university_id=university_id,
            base_url=base_url,
            scrape_url=scrape_url,
            **merged,
        )
    except Exception as exc:
        log.error(
            "Failed to build UniConfig for slug=%r: %s — falling back to bare defaults",
            slug,
            exc,
        )
        return UniConfig(
            slug=slug,
            name=name,
            university_id=university_id,
            base_url=base_url,
            scrape_url=scrape_url,
        )


def get_config_for_host(
    *,
    hostname: str,
    name: str,
    scrape_url: str,
    university_id: int | None = None,
    db_scrape_config: dict[str, Any] | None = None,
) -> UniConfig:
    """Convenience wrapper: derive slug from hostname then call ``load_uni_config``."""
    slug = _hostname_to_slug(hostname)
    return load_uni_config(
        slug=slug,
        name=name,
        scrape_url=scrape_url,
        university_id=university_id,
        db_scrape_config=db_scrape_config,
    )
