from __future__ import annotations

import importlib.util
import os
import uuid
from pathlib import Path

import pytest
from alembic.migration import MigrationContext
from alembic.operations import Operations
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from app.config import settings


MIGRATION_PATH = (
    Path(__file__).parents[1]
    / "alembic"
    / "versions"
    / "381_academic_requirement_option_mapping.py"
)

DEGREE_MAPPING = {
    "Master": "bachelors_equivalent",
    "Master's": "bachelors_equivalent",
    "Graduate Certificate & Diploma": "bachelors_equivalent",
    "Graduate Certificate": "bachelors_equivalent",
    "Graduate Diploma": "bachelors_equivalent",
    "Doctor": "masters_equivalent",
    "Doctorate": "masters_equivalent",
    "Doctor/Doctorate": "masters_equivalent",
    "PhD": "masters_equivalent",
    "Doctorate/PhD": "masters_equivalent",
    "Doctorate / PhD": "masters_equivalent",
    "Associate Degree": "grade_12_equivalent",
    "Associate Degree or Equivalent": "grade_12_equivalent",
    "Certificate & Diploma": "grade_12_equivalent",
    "Certificate": "grade_12_equivalent",
    "Diploma": "grade_12_equivalent",
    "Advanced Diploma": "grade_12_equivalent",
    "Bachelor": "grade_12_equivalent",
    "Bachelor's": "grade_12_equivalent",
}

OPTION_ROWS = (
    (11, "Grade 12th or equivalent", 1),
    (12, "Bachelor's degree or equivalent", 3),
    (13, "Master's degree or equivalent", 7),
    (14, "Doctorate / PhD", 8),
    (15, "Grade 10th or equivalent", 9),
)
OPTION_BY_KEY = {
    "grade_12_equivalent": (11, "Grade 12th or equivalent"),
    "bachelors_equivalent": (12, "Bachelor's degree or equivalent"),
    "masters_equivalent": (13, "Master's degree or equivalent"),
    "doctorate_phd": (14, "Doctorate / PhD"),
    "grade_10_equivalent": (15, "Grade 10th or equivalent"),
}


def _load_migration():
    spec = importlib.util.spec_from_file_location(
        "academic_requirement_option_mapping_migration",
        MIGRATION_PATH,
    )
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _run_migration(sync_connection, module, direction: str) -> None:
    previous_op = module.op
    module.op = Operations(MigrationContext.configure(sync_connection))
    try:
        getattr(module, direction)()
    finally:
        module.op = previous_op


@pytest.mark.asyncio
async def test_academic_level_migration_roundtrip_preserves_all_mappings():
    if os.environ.get("ALLOW_ISOLATED_SCHEMA_MIGRATION_TESTS") != "1":
        pytest.skip(
            "set ALLOW_ISOLATED_SCHEMA_MIGRATION_TESTS=1 only on a disposable "
            "development/test database"
        )
    schema = f"test_acad_level_{uuid.uuid4().hex}"
    quoted_schema = f'"{schema}"'
    engine = create_async_engine(settings.database_url)

    try:
        async with engine.begin() as connection:
            await connection.execute(text(f"CREATE SCHEMA {quoted_schema}"))
            await connection.execute(text(f"SET LOCAL search_path TO {quoted_schema}"))
            await connection.execute(text("""
                CREATE TABLE academic_level_options (
                    id integer PRIMARY KEY,
                    name text NOT NULL,
                    sort_order integer NOT NULL
                )
            """))
            await connection.execute(text("""
                CREATE TABLE courses (
                    id integer PRIMARY KEY,
                    degree_level text
                )
            """))
            await connection.execute(text("""
                CREATE TABLE academic_requirements (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    course_id integer NOT NULL REFERENCES courses(id),
                    academic_level text,
                    academic_score double precision,
                    score_type text,
                    academic_country text
                )
            """))
            await connection.execute(text("""
                CREATE TABLE scraped_courses (
                    id integer PRIMARY KEY,
                    academic_level text
                )
            """))
            await connection.execute(text("""
                CREATE TABLE academic_requirements_backup (
                    id integer,
                    course_id integer,
                    academic_level text
                )
            """))

            for option_id, name, sort_order in OPTION_ROWS:
                await connection.execute(
                    text("""
                        INSERT INTO academic_level_options (id, name, sort_order)
                        VALUES (:id, :name, :sort_order)
                    """),
                    {"id": option_id, "name": name, "sort_order": sort_order},
                )

            for course_id, degree_level in enumerate(DEGREE_MAPPING, start=1):
                await connection.execute(
                    text("""
                        INSERT INTO courses (id, degree_level)
                        VALUES (:id, :degree_level)
                    """),
                    {"id": course_id, "degree_level": degree_level},
                )
                # Exercise both migration paths: update existing requirements
                # and create missing rows for courses without one.
                if course_id % 2:
                    await connection.execute(
                        text("""
                            INSERT INTO academic_requirements
                                (course_id, academic_level, academic_score)
                            VALUES (:course_id, 'legacy value', 75)
                        """),
                        {"course_id": course_id},
                    )
            await connection.execute(text("""
                INSERT INTO scraped_courses (id, academic_level)
                VALUES (1, 'legacy staged value')
            """))

            migration = _load_migration()
            await connection.run_sync(
                lambda sync_connection: _run_migration(
                    sync_connection, migration, "upgrade"
                )
            )

            mapped = (
                await connection.execute(text("""
                    SELECT c.degree_level, alo.id, alo.name, alo.mapping_key
                    FROM courses c
                    JOIN academic_requirements ar ON ar.course_id = c.id
                    JOIN academic_level_options alo
                      ON alo.id = ar.academic_level_option_id
                    ORDER BY c.id
                """))
            ).all()
            assert {
                degree: (option_id, option_name, mapping_key)
                for degree, option_id, option_name, mapping_key in mapped
            } == {
                degree: (*OPTION_BY_KEY[mapping_key], mapping_key)
                for degree, mapping_key in DEGREE_MAPPING.items()
            }
            assert (
                await connection.execute(text("""
                    SELECT count(*)
                    FROM academic_requirements ar
                    JOIN courses c ON c.id = ar.course_id
                    WHERE c.id % 2 = 1
                      AND ar.academic_score = 75
                """))
            ).scalar_one() == len(DEGREE_MAPPING) // 2 + 1
            assert (
                await connection.execute(text("""
                    SELECT count(*)
                    FROM courses c
                    WHERE lower(trim(c.degree_level)) IN (
                        'master', 'master''s',
                        'graduate certificate & diploma',
                        'graduate certificate', 'graduate diploma',
                        'doctor', 'doctorate', 'doctor/doctorate', 'phd',
                        'doctorate/phd', 'doctorate / phd',
                        'associate degree', 'associate degree or equivalent',
                        'certificate & diploma', 'certificate', 'diploma',
                        'advanced diploma', 'bachelor', 'bachelor''s'
                    )
                    AND NOT EXISTS (
                        SELECT 1
                        FROM academic_requirements ar
                        WHERE ar.course_id = c.id
                          AND ar.academic_level_option_id IS NOT NULL
                    )
                """))
            ).scalar_one() == 0

            # Model an option-backed staged row restored from a snapshot.
            masters_option_id = (
                await connection.execute(text("""
                    SELECT id FROM academic_level_options
                    WHERE mapping_key = 'masters_equivalent'
                """))
            ).scalar_one()
            await connection.execute(
                text("""
                    UPDATE scraped_courses
                    SET academic_level = NULL,
                        academic_level_option_id = :option_id
                    WHERE id = 1
                """),
                {"option_id": masters_option_id},
            )

            await connection.run_sync(
                lambda sync_connection: _run_migration(
                    sync_connection, migration, "downgrade"
                )
            )
            assert (
                await connection.execute(text("""
                    SELECT academic_level FROM scraped_courses WHERE id = 1
                """))
            ).scalar_one() == "Master's degree or equivalent"
            assert (
                await connection.execute(text("""
                    SELECT count(*)
                    FROM academic_requirements ar
                    JOIN courses c ON c.id = ar.course_id
                    JOIN (VALUES
                        ('Master', 'Bachelor''s degree or equivalent'),
                        ('Master''s', 'Bachelor''s degree or equivalent'),
                        ('Graduate Certificate & Diploma', 'Bachelor''s degree or equivalent'),
                        ('Graduate Certificate', 'Bachelor''s degree or equivalent'),
                        ('Graduate Diploma', 'Bachelor''s degree or equivalent'),
                        ('Doctor', 'Master''s degree or equivalent'),
                        ('Doctorate', 'Master''s degree or equivalent'),
                        ('Doctor/Doctorate', 'Master''s degree or equivalent'),
                        ('PhD', 'Master''s degree or equivalent'),
                        ('Doctorate/PhD', 'Master''s degree or equivalent'),
                        ('Doctorate / PhD', 'Master''s degree or equivalent'),
                        ('Associate Degree', 'Grade 12th or equivalent'),
                        ('Associate Degree or Equivalent', 'Grade 12th or equivalent'),
                        ('Certificate & Diploma', 'Grade 12th or equivalent'),
                        ('Certificate', 'Grade 12th or equivalent'),
                        ('Diploma', 'Grade 12th or equivalent'),
                        ('Advanced Diploma', 'Grade 12th or equivalent'),
                        ('Bachelor', 'Grade 12th or equivalent'),
                        ('Bachelor''s', 'Grade 12th or equivalent')
                    ) expected(degree_level, academic_level)
                      ON expected.degree_level = c.degree_level
                    WHERE ar.academic_level = expected.academic_level
                """))
            ).scalar_one() == len(DEGREE_MAPPING)

            await connection.run_sync(
                lambda sync_connection: _run_migration(
                    sync_connection, migration, "upgrade"
                )
            )
            assert (
                await connection.execute(text("""
                    SELECT count(*)
                    FROM courses c
                    WHERE NOT EXISTS (
                        SELECT 1
                        FROM academic_requirements ar
                        WHERE ar.course_id = c.id
                          AND ar.academic_level_option_id IS NOT NULL
                    )
                """))
            ).scalar_one() == 0
            remapped = (
                await connection.execute(text("""
                    SELECT c.degree_level, alo.id, alo.name, alo.mapping_key
                    FROM courses c
                    JOIN academic_requirements ar ON ar.course_id = c.id
                    JOIN academic_level_options alo
                      ON alo.id = ar.academic_level_option_id
                    ORDER BY c.id
                """))
            ).all()
            assert {
                degree: (option_id, option_name, mapping_key)
                for degree, option_id, option_name, mapping_key in remapped
            } == {
                degree: (*OPTION_BY_KEY[mapping_key], mapping_key)
                for degree, mapping_key in DEGREE_MAPPING.items()
            }
            # Re-upgrade keeps the effective staged value even though the
            # migration deliberately derives option IDs only for live courses.
            assert (
                await connection.execute(text("""
                    SELECT academic_level FROM scraped_courses WHERE id = 1
                """))
            ).scalar_one() == "Master's degree or equivalent"
    finally:
        async with engine.begin() as connection:
            await connection.execute(
                text(f"DROP SCHEMA IF EXISTS {quoted_schema} CASCADE")
            )
        await engine.dispose()