export const CATEGORIES: Record<string, string[]> = {
  "Agriculture & Environmental Studies": [
    "Agriculture",
    "Animal Sciences",
    "Aquaculture & Fisheries",
    "Forestry",
    "Horticulture",
    "Plant & Crop Sciences",
    "Biodiversity & Conservation",
    "Climate Studies & Meteorology",
    "Earth Sciences",
    "Ecology",
    "Environmental Sciences",
    "Geology",
    "Hydrology & Water Management",
    "Natural Resource Management",
    "Sustainable Development",
    "Toxicology",
    "Food Science",
    "Veterinary Science",
    "Development Policies",
  ],
  "Architecture, Building & Design": [
    "Architecture",
    "Design",
    "Building",
    "Fashion Design",
    "Graphic Design",
    "User Experience Design",
    "Industrial Design",
    "Interior Design",
  ],
  "Arts, Humanities & Social Sciences": [
    "Arts",
    "Humanities",
    "Social Sciences",
    "Creative Writing",
    "General Studies & Classics",
    "History",
    "Liberal Arts",
    "Literature",
    "Linguistics",
    "Philosophy & Ethics",
    "Gender & Sexuality Studies",
    "International Relations",
    "Political Science",
    "Psychology",
    "Public Policy",
    "Sociology",
    "Leadership",
  ],
  "Business & Management": [
    "Accounting",
    "Business",
    "Actuarial Science",
    "Agribusiness",
    "Human Resource Management",
    "Auditing",
    "Enterprise Resource Planning Management",
    "Business Administration",
    "Business Intelligence & Analytics",
    "Commerce",
    "Finance",
    "Marketing",
    "Management",
    "Project Management",
    "Economics",
    "Quality Assurance & Management",
    "Manufacturing",
    "Real Estate & Trading",
  ],
  "Computer Science & IT": [
    "Artificial Intelligence",
    "Information Technology (IT)",
    "Business Information Systems",
    "Computer Science",
    "Cyber Security",
    "Networking",
    "Data Science & Big Data",
    "Software Engineering",
    "Video Games & Multimedia",
    "Web Technologies & Cloud Computing",
    "3D Arts and Animation",
  ],
  "Education & Social Work": [
    "Education",
    "Coaching",
    "Counselling",
    "Early Childhood Education",
    "Educational Research",
    "Pedagogy",
    "Teaching",
    "Social Work",
  ],
  "Engineering & Technology": [
    "Aerospace Engineering",
    "Automotive Engineering",
    "Bio & Biomedical Engineering",
    "Chemical Engineering",
    "Civil Engineering & Construction",
    "Electrical Engineering",
    "Electronics Engineering",
    "Energy & Power Engineering",
    "Environmental Engineering",
    "General Engineering & Technology",
    "Industrial & Systems Engineering",
    "Marine Engineering",
    "Engineering Management",
    "Materials Science & Engineering",
    "Mechanical Engineering",
    "Mechatronics",
    "Mining Oil & Gas",
    "Robotics",
    "Aviation",
    "Sustainable Energy",
    "Transportation",
  ],
  "Languages & Culture": [
    "Area & Cultural Studies",
    "Islamic Studies",
    "Languages",
    "TESOL",
    "Christian Studies",
  ],
  "Law & Criminology": [
    "Business Law",
    "Criminology",
    "Law",
    "Civil & Private Law",
    "Criminal Law",
    "International Law",
    "Legal Studies",
    "Patent & Intellectual Property Law",
    "Public Law",
    "Terrorism & Security",
  ],
  "Maths & Sciences": [
    "Applied Mathematics",
    "Science",
    "Astronomy & Space Sciences",
    "Biochemistry",
    "Biotechnology",
    "Chemistry",
    "Financial Mathematics",
    "Dermal Science",
    "Genetics",
    "Physics",
    "Statistics",
    "Biology",
    "Mathematics",
  ],
  "Media & Communications": [
    "Journalism",
    "Communications",
    "Media Management",
    "Media Studies & Mass Media",
    "Public Relations",
    "Media Marketing",
    "Translation & Interpreting",
    "Film Photography & Media",
  ],
  "Medicine & Health": [
    "Biomedicine",
    "Biomedical Sciences",
    "Clinical Psychology",
    "Complementary & Alternative Medicine",
    "Dentistry",
    "Health Sciences",
    "Human Medicine",
    "Midwifery",
    "Nursing",
    "Nutrition & Dietetics",
    "Pharmacy",
    "Physiotherapy",
    "Public Health",
    "Pharmaceutical",
    "Laboratory Medicine",
    "Community Services",
    "Community Health",
    "Ageing & Aged Care",
    "Veterinary Medicine",
    "Psychotherapy",
    "Health & Social Care",
  ],
  "Music & Performing Arts": [
    "Music",
    "Music History",
    "Visual Arts",
  ],
  "Sports & Personal Services": [
    "Sports Management",
    "Sports Science",
    "Beauty Therapy",
    "Exercise Sciences",
  ],
  "Tourism & Hospitality": [
    "Culinary Arts",
    "Event Management",
    "Hospitality Management",
    "Tourism",
  ],
};

export const CATEGORY_NAMES = Object.keys(CATEGORIES).sort();

export const DEGREE_LEVELS = [
  "Associate Degree or Equivalent",
  "Certificate & Diploma",
  "Pathway to Undergraduate",
  "Bachelor",
  "Graduate Certificate & Diploma",
  "Master",
  "Bachelor Dual Degree",
  "Master Dual Degree",
  "Dual Degree",
  "Doctor/Doctorate",
  "English Language",
];

export const STUDY_MODES = ["On Campus", "Online", "Both"];

export const STUDY_LOADS = ["Full Time", "Part Time", "Both"];

export const INTAKE_MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export const FEE_TERMS = ["Per Year", "Per Semester", "Per Subject", "Total"];

export const CURRENCIES = ["AUD", "USD", "GBP", "EUR", "NZD", "CAD", "SGD"];

export const ENGLISH_TEST_TYPES = ["IELTS", "PTE", "TOEFL", "Duolingo", "Cambridge", "Other"];

export function getSubCategories(category: string): string[] {
  return CATEGORIES[category] ?? [];
}
